"""add_field_for_product

Revision ID: 532137d6b0f4
Revises: 87987856cfc8
Create Date: 2024-02-24 22:01:34.325069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "532137d6b0f4"
down_revision: Union[str, None] = "87987856cfc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("image_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "image_id")
    # ### end Alembic commands ###
