DEFAULT_DB_URL = "postgresql+asyncpg://postgres:postgres@0.0.0.0:5438/postgres"

DEFAULT_DB_ECHO = False

DEFAULT_SECRET_KEY = "V/t26S4SzJy1eOVj7i6+3+8AovWYWZWoqHsZY+/VXtY="

DEFAULT_ALGORITHM = "HS256"

DEFAULT_MODE = "DEV"
DEFAULT_REDIS_HOST = "localhost"
DEFAULT_REDIS_PORT = 6379
